// flow-typed signature: b42580435d664d4be1d2cca050e69820
// flow-typed version: <<STUB>>/exorcist_v^0.4.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exorcist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'exorcist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'exorcist/bin/exorcist' {
  declare module.exports: any;
}

declare module 'exorcist/example/bar' {
  declare module.exports: any;
}

declare module 'exorcist/example/build' {
  declare module.exports: any;
}

declare module 'exorcist/example/foo' {
  declare module.exports: any;
}

declare module 'exorcist/example/main' {
  declare module.exports: any;
}

declare module 'exorcist/test/exorcist' {
  declare module.exports: any;
}

declare module 'exorcist/test/fixtures/bundle' {
  declare module.exports: any;
}

declare module 'exorcist/test/fixtures/bundle.nomap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'exorcist/bin/exorcist.js' {
  declare module.exports: $Exports<'exorcist/bin/exorcist'>;
}
declare module 'exorcist/example/bar.js' {
  declare module.exports: $Exports<'exorcist/example/bar'>;
}
declare module 'exorcist/example/build.js' {
  declare module.exports: $Exports<'exorcist/example/build'>;
}
declare module 'exorcist/example/foo.js' {
  declare module.exports: $Exports<'exorcist/example/foo'>;
}
declare module 'exorcist/example/main.js' {
  declare module.exports: $Exports<'exorcist/example/main'>;
}
declare module 'exorcist/index' {
  declare module.exports: $Exports<'exorcist'>;
}
declare module 'exorcist/index.js' {
  declare module.exports: $Exports<'exorcist'>;
}
declare module 'exorcist/test/exorcist.js' {
  declare module.exports: $Exports<'exorcist/test/exorcist'>;
}
declare module 'exorcist/test/fixtures/bundle.js' {
  declare module.exports: $Exports<'exorcist/test/fixtures/bundle'>;
}
declare module 'exorcist/test/fixtures/bundle.nomap.js' {
  declare module.exports: $Exports<'exorcist/test/fixtures/bundle.nomap'>;
}
