// flow-typed signature: b22b463a5c5e9a7af1e1c3829a6244c1
// flow-typed version: <<STUB>>/npm-run-help_v^1.1.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-run-help'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-run-help' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'npm-run-help/index' {
  declare module.exports: $Exports<'npm-run-help'>;
}
declare module 'npm-run-help/index.js' {
  declare module.exports: $Exports<'npm-run-help'>;
}
